### PR TITLE
style: simplify some statements for readability

### LINKED ISSUE #176: Some statements can be simplified for readability
We can replace lines like

```rust
let file_name = format!("{}_{}.{}", file_name, slab_index, extension);
```

with

```rust
let file_name = format!("{file_name}_{slab_index}.{extension}");
```

to improve code maintainability and developer productivity.

### PR DESCRIPTION
**Pull request by hamirmahal**
Closes #176

### CODE REVIEW

**Review by hamirmahal — COMMENTED** [review]
I ran CI on a fork. All checks passed.

**Comment by hamirmahal** [comment]
> I ran CI on a fork. All checks passed.

https://github.com/hamirmahal/copper-rs

**Comment by gbin** [comment]
indeed, thanks

**Comment by hamirmahal** [comment]
You're welcome.

**Pull request merged**
