### PR TITLE
Fixes #117: coredump on exit for balancebot-sim

### LINKED ISSUE #117: balancebot-sim coredumps  on exit
This is annoying to test the log creation.

### PR DESCRIPTION
**Pull request by gbin**
The root cause was that by default bevy/wgpu tries out a bunch of backends and puts the graphic stack in a weird state.

By forcing the backend it ends the process cleanly.

### CODE REVIEW

**Comment by mik90** [comment]
pulled the branch and ran

```bash
cd examples/cu_rp_balancebot
cargo r balancebot-sim
```

and saw

```
thread 'main' panicked at core/cu29_unifiedlog/src/lib.rs:458:29:
Failed to open file: logs/balance_0.copper
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `balancebot_sim::setup_copper`!
2024-12-01T22:53:07.678881Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped.
2024-12-01T22:53:07.678933Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped.
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
```

Seems like an unrelated error with log setup in balancebot-sim

**Comment by mik90** [comment]
Since i dont have a balancebot to produce logs, i copied the test.copper logs

```
# cd to root of repo
mkdir copper
cp core/cu29_export/test/test.copper logs/balance_0.copper
cargo  r -p cu-rp-balancebot  --bin balancebot-sim
```

The sim GUI popped up. When i closed the sim GUI, my terminal was messed up and I assume it was dumping the consolemon TUI to the terminal or something.

Didn't see any coredumps though

**Comment by mik90** [comment]
Different applications tend to prefer one backend or another, idk what's best for bevy but I imagine that defaulting to Vulkan on linux is fine.

**Comment by gbin** [comment]
> Since i dont have a balancebot to produce logs, i copied the test.copper logs
> 
> ```
> # cd to root of repo
> mkdir copper
> cp core/cu29_export/test/test.copper logs/balance_0.copper
> cargo  r -p cu-rp-balancebot  --bin balancebot-sim
> ```
> 
> The sim GUI popped up. When i closed the sim GUI, my terminal was messed up and I assume it was dumping the consolemon TUI to the terminal or something.
> 
> Didn't see any coredumps though

Whenever you run the sim it should produce valid logs for you

**Comment by gbin** [comment]
> pulled the branch and ran
> 
> ```shell
> cd examples/cu_rp_balancebot
> cargo r balancebot-sim
> ```
> 
> and saw
> 
> ```
> thread 'main' panicked at core/cu29_unifiedlog/src/lib.rs:458:29:
> Failed to open file: logs/balance_0.copper
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> Encountered a panic in system `balancebot_sim::setup_copper`!
> 2024-12-01T22:53:07.678881Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped.
> 2024-12-01T22:53:07.678933Z  WARN bevy_ecs::world::command_queue: CommandQueue has un-applied commands being dropped.
> Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
> ```
> 
> Seems like an unrelated error with log setup in balancebot-sim. This is on Fedora linux

do you have a "logs" directory from where you run it from ? I just changed it on this branch to log to logs/ instead of the current path.

**Pull request merged**
